apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: pct-scale
spec:
  version: "{{ .TagName }}"
  homepage: https://github.com/tuannvm/scale-pct
  shortDescription: >-
    Scale Kubernetes deployment base on percentage
  description: |+2
    Scale Kubernetes deployment base on percentage

    # Scale up a deployment named 'foo' by 10%
    $ kubectl pct scale --pct=10 deployment/foo
    # Scale down a deployment named 'foo' by 10%
    $ kubectl pct scale --pct=-10 deployment/foo

    For detail, run:

    $ kubectl pct scale -h
  caveats: |
    The plugin requires the rights to patch (Cluster)Role and (Cluster)RoleBindings.
  platforms:
    - selector:
        matchLabels:
          os: darwin
          arch: amd64
      {{addURIAndSha "https://github.com/tuannvm/scale-pct/releases/download/{{ .TagName }}/scale-pct_{{ .TagName }}_darwin_amd64.tar.gz" .TagName | indent 6}}
      files:
        - from: kubectl-pct-scale
          to: .
        - from: LICENSE
          to: .
      bin: kubectl-pct-scale
    - selector:
        matchLabels:
          os: linux
          arch: amd64
      {{addURIAndSha "https://github.com/tuannvm/scale-pct/releases/download/{{ .TagName }}/scale-pct_{{ .TagName }}_linux_amd64.tar.gz" .TagName | indent 6}}
      files:
        - from: kubectl-pct-scale
          to: .
        - from: LICENSE
          to: .
      bin: kubectl-pct-scale